# Generated by Django 3.2 on 2021-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='openInsider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=200)),
                ('insiderName', models.CharField(max_length=50)),
                ('insiderLink', models.CharField(max_length=200)),
                ('insiderID', models.CharField(max_length=50)),
                ('insiderTitle', models.CharField(max_length=200)),
                ('tradeType', models.CharField(max_length=50)),
                ('tradePrice', models.CharField(max_length=200)),
                ('tradeQuantity', models.CharField(max_length=50)),
                ('stocksOwned', models.CharField(max_length=200)),
                ('stockPercent', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
